declare @ORDER_QTY ot_account,@cuohe float,@date nvarchar(30),@no int,@len INT,@STK_CODE VARCHAR(8),@CUACCT_CODE ot_account
set @date = CONVERT(nvarchar(30),getdate(),112)
set @ORDER_QTY=0
set @cuohe = '2' 
set @no = 1
set @len = 0
set @STK_CODE=510020
set @CUACCT_CODE=88850238

SELECT A1.STK_CODE,
	A1.ETF_CODE,
	A1.STKBD,
	A1.STK_CLS,
    A1.PRICE AS ORDER_PRICE,
	'100' STK_BIZ,
	'100' STK_BIZ_ACTION,
	'0' SECURITY_LEVEL,
	A1.ORDER_QTY,
	B1.USER_CODE CUST_CODE,
	B1.CUACCT_CODE,
	B1.STKPBU,
	B1.TRDACCT
	FROM 		
	(SELECT 
		case when  B.CURRENT_PRICE <> 0 AND B.CURRENT_PRICE <> '' then   ROUND(B.CURRENT_PRICE/10000.000,3,1) 
			when (B.CURRENT_PRICE = 0 or B.CURRENT_PRICE = '') AND  B.CLOSING_PRICE <> 0 AND  B.CLOSING_PRICE <> '' THEN  ROUND(B.CLOSING_PRICE/10000.000,3,1)
		ELSE 1 END as PRICE,	-- 委托价格
		A.COMP_STK_CODE as STK_CODE,
		A.ETF_CODE,
		A.STKBD,
		C.STK_CLS,
		A.STK_QTY AS ORDER_QTY		 
	FROM (SELECT b.COMP_STK_CODE,b.STKBD,b.STK_QTY,b.ETF_CODE FROM STK_ETF_INFO a,STK_ETF_BASKET b
	WHERE a.ETF_CODE=b.ETF_CODE AND a.ETF_TYPE IN ('1','3') AND b.ETF_INSTEAD_FLAG IN ('0','1') AND b.STKEX=b.COMPONET_STKEX AND LEN(b.COMP_STK_CODE)=6 AND a.ETF_CODE=@STK_CODE) A
	INNER JOIN STK_MKTINFO B ON A.COMP_STK_CODE=B.STK_CODE
	INNER JOIN STK_INFO C ON A.COMP_STK_CODE=C.STK_CODE ) A1
INNER JOIN 		
	(SELECT C.USER_CODE,
	       C.CUACCT_CODE,
	       C.FUND_STATUS,
	       D.STKBD,
	       D.STKPBU,
	       D.TRDACCT
	FROM (SELECT * FROM CUACCT_FUND WHERE FUND_AVL/1000>100000 AND CUACCT_CODE  not IN (SELECT CUACCT_CODE  FROM CUACCT_CHANNEL_CFG )
    ) C
	INNER JOIN (SELECT * FROM STK_TRDACCT WHERE TRDACCT_STATUS = '0' AND  TRDACCT_EXCLS in ('0','1') AND STKPBU <> ' '
    ) D 
	ON C.CUACCT_CODE = D.CUACCT_CODE
	INNER JOIN (SELECT CUST_CODE FROM CUST_AGREEMENT WHERE EXP_DATE>@date AND (CUST_AGMT_TYPE IN ('2C', '2k', 'M') or CUST_AGMT_TYPE IN ('2C', 'A', 'M'))
    GROUP BY CUST_CODE
    HAVING COUNT(DISTINCT CUST_AGMT_TYPE) >= 3
    ) E  --成分股全部买成要求账户必须同时存在3个协议
	ON D.CUST_CODE = E.CUST_CODE
	WHERE STKBD IN ('00','10') AND C.CUACCT_CODE=@CUACCT_CODE
	GROUP BY C.USER_CODE,
	       C.CUACCT_CODE,
	       C.FUND_STATUS,
	       D.STKBD,
	       D.STKPBU,
	       D.TRDACCT
					) B1 ON A1.STKBD=B1.STKBD